#项目信息
server:
  context-path: /drug_store
  port: 8080
    
#log配置
logging:
  config: classpath:logback-spring.xml
  
#改变控制台的颜色
AnsiColor: BRIGHT_YELLOW
  
#监控 http://localhost:8333/eht/monitoring
javamelody:
  enabled: true
  advisor-auto-proxy-creator-enabled: false
  


#多数据源配置
#主数据源E2306
master:
  datasource:
   #driverClassName: oracle.jdbc.driver.OracleDriver
   #url: jdbc:oracle:thin:@39.98.48.207:3306:PHARMACY
   driverClassName: com.mysql.jdbc.Driver
   url: jdbc:mysql://39.98.48.207:3306/pharmacydata?serverTimezone=GMT%2B8&useSSL=FALSE
   username: PHARMACY  
   password: YSK123456
   initialSize: 1 # 初始化大小
      
#数据源的属性
spring:
  datasource:
    minIdle: 5
    maxActive: 20
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true      # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 0
    filters: stat,wall,log4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true
    type: com.alibaba.druid.pool.DruidDataSource

#动态代理方式
  aop:
    auto: true
    proxy-target-class: false

  output:
    ansi:
      enabled: always
      
#配置fastjson转换器
  http:
    converters:
      preferred-json-mapper: fastjson 
    encoding:
      force: true
      enabled: true
   
#配置图片上传大小
    multipart:
      max-file-size: 100MB  #单个文件
      max-request-size: 300MB  #总文件
      enabled: true
      
#redis配置
  redis:
    database: 1   #数据库索引 默认0为处理订单失效事件index ，将其他缓存放到index1中 ，
    host: 192.168.1.106 #redis 服务器地址
    port: 6379  #redis 服务器连接端口
    password:   redis      #服务器连接密码  默认为空
    pool:
      max-active: 10       #连接池最大连接数
      max-wait: 1         #连接池最大阻塞等待时间
      max-idle: 10        #连接池最大空闲连接
      min-idle: 5        #连接池最小空闲连接
    timeout: 0            #连接超时时间（毫秒）  
    
  rabbitmq:
    host: 192.168.1.107
    port: 5672
    username: admin
    password: admin
    
    #设置环境      测试环境 test,开发环境dev,生产环境prod
  profiles:
    active:
    - dev